name: Unzip File

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Unzip the file
      - name: Extract contents of volcano-mobile-pwa.zip
        run: |
          unzip volcano-mobile-pwa.zip -d .
          ls -l

      # Step 3: Commit and push unzipped files
      - name: Commit and push unzipped files
        run: |
          git config --global user.name "vahidking75"
          git config --global user.email "vahid.king62@gmail.com"
          git add .
          git commit -m "Unzipped volcano-mobile-pwa.zip contents" || echo "No changes to commit"
          git push origin main
